import { generateCustomerId } from '@logto/shared';

/**
 * Describes a `custom_data` key whose value is auto-generated at user creation time.
 * If the key is absent from the caller-supplied `customData`, `generate()` is called
 * and the result is stored under that key before the user record is inserted.
 */
export type AutoGeneratedCustomDataClaim = {
  /** Key used in `custom_data`. Must be snake_case. */
  key: string;
  /** Called once at user creation when the key is not already present in `custom_data`. */
  generate: () => string;
};

/**
 * Claims that are auto-generated and written into `custom_data` when a user is created.
 *
 * To add a new auto-generated claim:
 *  1. Append an entry with a unique `key` and a `generate` function.
 *  2. No schema migration is required — values live in the existing `custom_data` column.
 */
export const autoGeneratedCustomDataClaims: AutoGeneratedCustomDataClaim[] = [
  {
    /**
     * A 10-digit random numeric string used as a stable, human-friendly customer
     * identifier. Stored as `custom_data.customer_id`.
     */
    key: 'customer_id',
    generate: generateCustomerId,
  },
];
